name: Date-based Versioning Action
description: Generate a version number
author: Ibrahim AshShohail
inputs:
  prefix:
    required: false
    default: ""
  suffix:
    required: false
    default: ""
  major-version:
    description: Major version
    required: true
    default: "0"
outputs:
  version:
    description: Version number
    value: ${{ steps.generator.outputs.patch }}
runs:
  using: "composite"
  steps:
    - id: generator
      shell: bash
      run: |
        V_MAJOR=${{ inputs.major-version }}
        V_MINOR=$V_MAJOR.$( TZ=UTC date +"%y%m%d" | sed -E 's/^0{1,3}//g' )
        V_PATCH=$V_MINOR.$( TZ=UTC date +"%H%M%S" | sed -E 's/^0{1,3}//g' )
        V_TIMESTAMP=$( TZ=UTC date '+%Y%m%d%H%M%S' )
        V_COMMIT=$( git rev-parse --short=12 HEAD )
        
        echo "timestamp=$V_TIMESTAMP" >> $GITHUB_OUTPUT
        echo "commit=$V_COMMIT" >> $GITHUB_OUTPUT

        echo "major=${{ inputs.prefix }}${V_MAJOR}${{ inputs.suffix }}" >> $GITHUB_OUTPUT
        echo "minor=${{ inputs.prefix }}${V_MINOR}${{ inputs.suffix }}" >> $GITHUB_OUTPUT
        echo "patch=${{ inputs.prefix }}${V_PATCH}${{ inputs.suffix }}" >> $GITHUB_OUTPUT
