name: Date-based Version
description: Generate a version number
author: Ibrahim AshShohail
inputs:
  prefix:
    required: false
    default: ""
  suffix:
    required: false
    default: ""
  major-version:
    description: Major version
    required: true
    default: "0"
outputs:
  version:
    description: Version number
    value: ${{ steps.generator.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: generator
      shell: bash
      run: |
        PREFIX=${{ inputs.prefix }}
        SUFFIX=${{ inputs.suffix }}
        V_MAJOR=${{ inputs.major-version }}
        V_MINOR=$V_MAJOR.$(date +"%y%m%d" | sed -E 's/^0{1,3}//g')
        V_PATCH=$V_MINOR.$(date +"%H%M%S" | sed -E 's/^0{1,3}//g')
        
        echo ::set-output name=version::$(date +"1.%y%m%d.%H%M%S" | sed -E 's/\.0{1,3}/./g')
        
        echo ::set-output name=version-major::${PREFIX}${V_MAJOR}${SUFFIX}
        echo ::set-output name=version-minor::${PREFIX}${V_MINOR}${SUFFIX}
        echo ::set-output name=version-patch::${PREFIX}${V_PATCH}${SUFFIX}
